require('dotenv').config();
const express=require('express');const path=require('path');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const cors=require('cors');const crypto=require('crypto');const fs=require('fs');const cookieParser=require('cookie-parser');const WebSocket=require('ws');
const app=express();const PORT=Number(process.env.PORT||3000);const BASE_URL=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,'');const PUBLIC_DIR=path.join(__dirname,'public');
const DERIV_CLIENT_ID=process.env.DERIV_CLIENT_ID||'';const DERIV_PUBLIC_APP_ID=process.env.DERIV_PUBLIC_APP_ID||'';const DERIV_AFFILIATE_PARAM=process.env.DERIV_AFFILIATE_PARAM||'t';const DERIV_AFFILIATE_TOKEN=process.env.DERIV_AFFILIATE_TOKEN||'';const DERIV_AFFILIATE_ID=process.env.DERIV_AFFILIATE_ID||'';const DERIV_CAMPAIGN=process.env.DERIV_CAMPAIGN||'protraders-fx';const DERIV_SCOPE=process.env.DERIV_SCOPE||'trade account_manage';const SESSION_SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
const DATA_FILE=path.join(__dirname,'data','analytics.json');fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});if(!fs.existsSync(DATA_FILE))fs.writeFileSync(DATA_FILE,JSON.stringify({visitors:0,registrations:0,events:[]},null,2));
function readData(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{return{visitors:0,registrations:0,events:[]}}}function writeData(d){fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2))}function base64url(b){return Buffer.from(b).toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}function key(){return crypto.createHash('sha256').update(SESSION_SECRET).digest()}function seal(obj){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const enc=Buffer.concat([c.update(JSON.stringify(obj),'utf8'),c.final()]);return `${base64url(iv)}.${base64url(c.getAuthTag())}.${base64url(enc)}`}function unseal(v){const [iv,tag,data]=String(v||'').split('.');if(!iv||!tag||!data)throw Error('invalid session');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8'))}
function verifier(){return base64url(crypto.randomBytes(64))}function challenge(v){return base64url(crypto.createHash('sha256').update(v).digest())}function session(req){try{const s=unseal(req.cookies?.protraders_session);if(!s||!s.accessToken||Date.now()>=s.expiresAt)return null;return s}catch{return null}}
const allowedOrigins=process.env.ALLOWED_ORIGINS?process.env.ALLOWED_ORIGINS.split(',').map(x=>x.trim()):[BASE_URL];app.use(cors({origin:allowedOrigins,credentials:true}));app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],connectSrc:["'self'",'https://auth.deriv.com','https://api.derivws.com','wss://*.derivws.com'],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https:'],frameAncestors:["'none'"]}},referrerPolicy:{policy:'strict-origin-when-cross-origin'}}));app.disable('x-powered-by');app.use(express.json({limit:'20kb'}));app.use(express.urlencoded({extended:false,limit:'20kb'}));app.use(cookieParser());app.use('/api/',rateLimit({windowMs:15*60*1000,max:180,standardHeaders:true,legacyHeaders:false}));
app.get('/api/config',(req,res)=>res.json({configured:Boolean(DERIV_CLIENT_ID&&DERIV_AFFILIATE_TOKEN),publicAppId:DERIV_PUBLIC_APP_ID,partnerParam:DERIV_AFFILIATE_PARAM,campaign:DERIV_CAMPAIGN}));
app.post('/api/track',(req,res)=>{const type=String(req.body?.type||'page_view').slice(0,40);const d=readData();if(type==='page_view')d.visitors++;d.events.push({type,at:new Date().toISOString(),path:String(req.body?.path||'/').slice(0,200)});if(d.events.length>5000)d.events=d.events.slice(-5000);writeData(d);res.status(204).end()});
app.get('/api/analytics',(req,res)=>{const d=readData();res.json({visitors:d.visitors,registrations:d.registrations||0,oauthSuccesses:d.events.filter(e=>e.type==='oauth_login_success'||e.type==='oauth_signup_success').length,fundedAccounts:null,note:'Funded-account status must be confirmed in Deriv Partner Hub; it is not fabricated here.'})});
function oauthUrl(req,mode){if(!DERIV_CLIENT_ID)throw Error('DERIV_CLIENT_ID is not configured');const v=verifier();const state=seal({verifier:v,mode,nonce:base64url(crypto.randomBytes(16)),iat:Date.now()});const p=new URLSearchParams({response_type:'code',client_id:DERIV_CLIENT_ID,redirect_uri:`${BASE_URL}/oauth/callback`,scope:DERIV_SCOPE,state,code_challenge:challenge(v),code_challenge_method:'S256'});if(mode==='signup'){if(!DERIV_AFFILIATE_TOKEN)throw Error('Deriv signup attribution is not configured');p.set('prompt','registration');p.set(DERIV_AFFILIATE_PARAM,DERIV_AFFILIATE_TOKEN);p.set('utm_campaign',DERIV_CAMPAIGN);p.set('utm_medium','affiliate');if(DERIV_AFFILIATE_ID)p.set('utm_source',DERIV_AFFILIATE_ID)}return `https://auth.deriv.com/oauth2/auth?${p.toString()}`}
app.get('/api/deriv/login',(req,res)=>{try{res.redirect(oauthUrl(req,'login'))}catch(e){res.status(503).json({error:e.message})}});app.get('/api/deriv/signup',(req,res)=>{try{res.redirect(oauthUrl(req,'signup'))}catch(e){res.status(503).json({error:e.message})}});
app.get('/oauth/callback',async(req,res)=>{try{if(req.query.error)return res.redirect(`/?oauth_error=${encodeURIComponent(String(req.query.error))}`);const p=unseal(req.query.state);if(!p?.verifier||!['login','signup'].includes(p.mode)||Date.now()-p.iat>600000)throw Error('Invalid or expired OAuth state');const body=new URLSearchParams({grant_type:'authorization_code',client_id:DERIV_CLIENT_ID,code:String(req.query.code||''),code_verifier:p.verifier,redirect_uri:`${BASE_URL}/oauth/callback`});const r=await fetch('https://auth.deriv.com/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error(`Token exchange failed (${r.status})`);const t=await r.json();if(!t.access_token)throw Error('No access token returned');const s=seal({accessToken:t.access_token,refreshToken:t.refresh_token||null,expiresAt:Date.now()+Number(t.expires_in||3600)*1000});res.cookie('protraders_session',s,{httpOnly:true,secure:BASE_URL.startsWith('https://'),sameSite:'lax',maxAge:Number(t.expires_in||3600)*1000,path:'/'});const d=readData();d.events.push({type:p.mode==='signup'?'oauth_signup_success':'oauth_login_success',at:new Date().toISOString()});if(p.mode==='signup'){d.registrations=(d.registrations||0)+1;d.events.push({type:'registration_complete',at:new Date().toISOString()})}writeData(d);res.redirect('/workspace.html')}catch(e){console.error(e.message);res.redirect('/?oauth_error=oauth_failed')}});
app.get('/api/session',(req,res)=>{const s=session(req);if(!s)return res.json({authenticated:false});res.json({authenticated:true,expiresAt:s.expiresAt})});app.post('/api/logout',(req,res)=>{res.clearCookie('protraders_session',{httpOnly:true,secure:BASE_URL.startsWith('https://'),sameSite:'lax',path:'/'});res.status(204).end()});
function derivRequest(accessToken,payload){return new Promise((resolve,reject)=>{const ws=new WebSocket(`wss://ws.derivws.com/websockets/v3?app_id=${encodeURIComponent(DERIV_PUBLIC_APP_ID||'1089')}`);let timer=setTimeout(()=>{try{ws.close()}catch{}reject(Error('Deriv request timeout'))},12000);ws.on('open',()=>ws.send(JSON.stringify({authorize:accessToken})));ws.on('message',raw=>{let d;try{d=JSON.parse(raw.toString())}catch{return}if(d.error){clearTimeout(timer);try{ws.close()}catch{};return reject(Error(d.error.message||'Deriv API error'))}if(d.msg_type==='authorize'){ws.send(JSON.stringify(payload));}else if(d.msg_type){clearTimeout(timer);try{ws.close()}catch{};resolve(d)}});ws.on('error',e=>{clearTimeout(timer);reject(e)});ws.on('close',()=>clearTimeout(timer));})}
app.get('/api/account',async(req,res)=>{const s=session(req);if(!s)return res.status(401).json({authenticated:false});try{const d=await derivRequest(s.accessToken,{balance:1});const a=d.balance||{};res.json({authenticated:true,balance:a.balance??null,currency:a.currency??null,loginid:a.loginid??null,openPnl:0})}catch(e){res.status(502).json({error:'Account data unavailable',message:e.message})}});
app.post('/api/trades',async(req,res)=>{const s=session(req);if(!s)return res.status(401).json({error:'Not authenticated'});const symbol=String(req.body?.symbol||'R_100');const type=['CALL','PUT'].includes(req.body?.contract_type)?req.body.contract_type:null;const stake=Number(req.body?.stake);const duration=Number(req.body?.duration);if(!type||!/^([A-Z0-9_]+)$/.test(symbol)||!Number.isFinite(stake)||stake<=0||!Number.isFinite(duration)||duration<1||duration>3600)return res.status(400).json({error:'Invalid trade parameters'});try{const account=await derivRequest(s.accessToken,{balance:1});const currency=account.balance?.currency||'USD';const proposal=await derivRequest(s.accessToken,{proposal:1,amount:stake,basis:'stake',contract_type:type,currency,duration,duration_unit:'t',symbol});if(!proposal.proposal?.id)return res.status(502).json({error:'Deriv did not return a proposal'});const buy=await derivRequest(s.accessToken,{buy:proposal.proposal.id,price:stake});if(buy.error)return res.status(502).json({error:buy.error.message});res.json({ok:true,message:`Trade opened on ${symbol}. Contract ${buy.buy?.contract_id||'created'}.`,contractId:buy.buy?.contract_id||null})}catch(e){res.status(502).json({error:'Trade request failed',message:e.message})}});
app.post('/api/bot',async(req,res)=>{const s=session(req);if(!s)return res.status(401).json({error:'Not authenticated'});const action=req.body?.action==='start'?'start':'stop';res.json({ok:true,message:action==='start'?'Free bot interface started in controlled mode. Live bot execution remains disabled until the bot adapter is separately tested.':'Free bot stopped.',execution:'interface_only'})});
app.get('/api/preflight',(req,res)=>res.json({productionBaseUrl:BASE_URL,redirectUri:`${BASE_URL}/oauth/callback`,https:BASE_URL.startsWith('https://'),oauthClientConfigured:Boolean(DERIV_CLIENT_ID),partnerTrackingConfigured:Boolean(DERIV_AFFILIATE_TOKEN),sessionSecretConfigured:Boolean(process.env.SESSION_SECRET),readyForControlledLiveTest:Boolean(BASE_URL.startsWith('https://')&&DERIV_CLIENT_ID&&DERIV_AFFILIATE_TOKEN&&process.env.SESSION_SECRET)}));
app.get('/health',(req,res)=>res.json({ok:true,service:'protraders-fx',time:new Date().toISOString()}));app.get('/app-config.js',(req,res)=>res.type('application/javascript').send(`window.PROTRADERS_PUBLIC_APP_ID=${JSON.stringify(DERIV_PUBLIC_APP_ID)};`));
app.get('/workspace',(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'workspace.html')));app.get('/workspace.html',(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'workspace.html')));
for(const p of ['marketplace','course','signals','manual','builder'])app.get('/'+p,(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'pages',p+'.html')));
app.use(express.static(PUBLIC_DIR,{extensions:['html']}));app.get('*',(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'index.html')));app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Internal server error'})});
app.listen(PORT,()=>console.log(`[PROTRADERS FX] running on ${BASE_URL}`));
