(() => {
  const names={R_100:'Volatility 100 Index',R_75:'Volatility 75 Index',R_50:'Volatility 50 Index',R_25:'Volatility 25 Index',R_10:'Volatility 10 Index','1HZ100V':'Volatility 100 (1s)','1HZ75V':'Volatility 75 (1s)'};
  const state={symbol:'R_100',prices:[],last:null,previous:null,bot:false};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const text=(s,v)=>{const e=$(s);if(e)e.textContent=v};
  const money=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8}):'—';
  async function track(type){try{await fetch('/api/track',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,path:location.pathname}),keepalive:true})}catch{}}
  track('workspace_view');
  function selectSymbol(symbol){state.symbol=symbol;state.prices=[];state.previous=null;$$('[data-symbol]').forEach(b=>b.classList.toggle('active',b.dataset.symbol===symbol));$('#tradeSymbol').value=symbol;text('#heroSymbol',names[symbol]||symbol);text('#chartSymbol',names[symbol]||symbol);text('#analysisSymbol',symbol);text('#botMarket',symbol);connectMarket();}
  $$('[data-symbol]').forEach(b=>b.addEventListener('click',()=>selectSymbol(b.dataset.symbol)));$('#tradeSymbol').addEventListener('change',e=>selectSymbol(e.target.value));
  $$('.timeframe').forEach(b=>b.addEventListener('click',()=>{$$('.timeframe').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
  function render(){const line=$('#chartLine');if(!line||state.prices.length<2)return;const a=state.prices.slice(-100),min=Math.min(...a),max=Math.max(...a),span=max-min||1;line.setAttribute('points',a.map((v,i)=>`${i/(a.length-1)*1000},${380-((v-min)/span)*340}`).join(' '));text('#chartAxis','');$('#chartAxis').innerHTML=[max,max-span*.25,max-span*.5,max-span*.75,min].map(v=>`<span>${money(v)}</span>`).join('');}
  function updatePrice(v){const n=Number(v);if(!Number.isFinite(n))return;state.previous=state.last;state.last=n;state.prices.push(n);if(state.prices.length>150)state.prices.shift();text('#heroPrice',money(n));text('#analysisPrice',money(n));const d=state.previous==null?0:n-state.previous,e=$('#heroMovement');e.classList.remove('positive','negative');if(d>0){e.classList.add('positive');e.textContent='+'+money(d)}else if(d<0){e.classList.add('negative');e.textContent=money(d)}else e.textContent='LIVE';text('#connectionStatus','LIVE MARKET FEED');text('#analysisStatus','LIVE');text('#signalState',d>0?'BUY BIAS':d<0?'SELL BIAS':'WAIT');$('#signalState').className=d>0?'buy':d<0?'sell':'wait';render();}
  let socket;
  function connectMarket(){if(socket)try{socket.close()}catch{};const appId=window.PROTRADERS_PUBLIC_APP_ID||'';if(!appId){text('#connectionStatus','MARKET DATA APP ID NOT CONFIGURED');return}socket=new WebSocket(`wss://ws.derivws.com/websockets/v3?app_id=${encodeURIComponent(appId)}`);socket.onopen=()=>socket.send(JSON.stringify({ticks:state.symbol,subscribe:1}));socket.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.tick?.quote)updatePrice(d.tick.quote)}catch{}};socket.onerror=()=>text('#connectionStatus','MARKET FEED ERROR');}
  async function loadSession(){try{const r=await fetch('/api/session');const s=await r.json();if(!s.authenticated){location.href='/';return}text('#accountChip','CONNECTED');text('#accountStatus','CONNECTED');text('#tradeMessage','Deriv account connected. Balance and trading requests are routed through the authenticated server session.');loadAccount();}catch{location.href='/';}}
  async function loadAccount(){try{const r=await fetch('/api/account');const d=await r.json();if(!r.ok)throw new Error(d.error||'account');text('#balance',d.balance!=null?`${d.balance} ${d.currency||''}`:'—');text('#currency',d.currency||'—');text('#loginid',d.loginid||'—');text('#pnl',d.openPnl!=null?`${d.openPnl}`:'0.00');}catch{text('#accountStatus','CONNECTED / DATA UNAVAILABLE');}}
  async function trade(direction){const msg=$('#tradeMessage');const payload={symbol:$('#tradeSymbol').value,contract_type:direction,stake:Number($('#stake').value),duration:Number($('#duration').value)};msg.textContent='Submitting validated trade request…';try{const r=await fetch('/api/trades',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();msg.textContent=d.message||d.error||'Trade request completed.';if(r.ok)loadAccount();}catch{msg.textContent='Trade request could not be completed.'}}
  $('#buyButton').addEventListener('click',()=>trade('CALL'));$('#sellButton').addEventListener('click',()=>trade('PUT'));
  $('#startBot').addEventListener('click',async()=>{state.bot=true;$('#startBot').disabled=true;$('#stopBot').disabled=false;text('#botStatus','RUNNING');await fetch('/api/bot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'start',symbol:state.symbol})}).catch(()=>{})});
  $('#stopBot').addEventListener('click',async()=>{state.bot=false;$('#startBot').disabled=false;$('#stopBot').disabled=true;text('#botStatus','STOPPED');await fetch('/api/bot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'stop',symbol:state.symbol})}).catch(()=>{})});
  $('#logoutButton').addEventListener('click',async()=>{await fetch('/api/logout',{method:'POST'}).catch(()=>{});location.href='/'});
  loadSession();connectMarket();
})();
